/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as gettingStartedSocialLinksProfileImport } from './routes/(getting-started)/social-links-profile'
import { Route as gettingStartedQrCodeComponentImport } from './routes/(getting-started)/qr-code-component'
import { Route as gettingStartedBlogPreviewCardImport } from './routes/(getting-started)/blog-preview-card'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const gettingStartedSocialLinksProfileRoute =
  gettingStartedSocialLinksProfileImport.update({
    id: '/(getting-started)/social-links-profile',
    path: '/social-links-profile',
    getParentRoute: () => rootRoute,
  } as any)

const gettingStartedQrCodeComponentRoute =
  gettingStartedQrCodeComponentImport.update({
    id: '/(getting-started)/qr-code-component',
    path: '/qr-code-component',
    getParentRoute: () => rootRoute,
  } as any)

const gettingStartedBlogPreviewCardRoute =
  gettingStartedBlogPreviewCardImport.update({
    id: '/(getting-started)/blog-preview-card',
    path: '/blog-preview-card',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(getting-started)/blog-preview-card': {
      id: '/(getting-started)/blog-preview-card'
      path: '/blog-preview-card'
      fullPath: '/blog-preview-card'
      preLoaderRoute: typeof gettingStartedBlogPreviewCardImport
      parentRoute: typeof rootRoute
    }
    '/(getting-started)/qr-code-component': {
      id: '/(getting-started)/qr-code-component'
      path: '/qr-code-component'
      fullPath: '/qr-code-component'
      preLoaderRoute: typeof gettingStartedQrCodeComponentImport
      parentRoute: typeof rootRoute
    }
    '/(getting-started)/social-links-profile': {
      id: '/(getting-started)/social-links-profile'
      path: '/social-links-profile'
      fullPath: '/social-links-profile'
      preLoaderRoute: typeof gettingStartedSocialLinksProfileImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog-preview-card': typeof gettingStartedBlogPreviewCardRoute
  '/qr-code-component': typeof gettingStartedQrCodeComponentRoute
  '/social-links-profile': typeof gettingStartedSocialLinksProfileRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog-preview-card': typeof gettingStartedBlogPreviewCardRoute
  '/qr-code-component': typeof gettingStartedQrCodeComponentRoute
  '/social-links-profile': typeof gettingStartedSocialLinksProfileRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(getting-started)/blog-preview-card': typeof gettingStartedBlogPreviewCardRoute
  '/(getting-started)/qr-code-component': typeof gettingStartedQrCodeComponentRoute
  '/(getting-started)/social-links-profile': typeof gettingStartedSocialLinksProfileRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog-preview-card'
    | '/qr-code-component'
    | '/social-links-profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog-preview-card'
    | '/qr-code-component'
    | '/social-links-profile'
  id:
    | '__root__'
    | '/'
    | '/(getting-started)/blog-preview-card'
    | '/(getting-started)/qr-code-component'
    | '/(getting-started)/social-links-profile'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  gettingStartedBlogPreviewCardRoute: typeof gettingStartedBlogPreviewCardRoute
  gettingStartedQrCodeComponentRoute: typeof gettingStartedQrCodeComponentRoute
  gettingStartedSocialLinksProfileRoute: typeof gettingStartedSocialLinksProfileRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  gettingStartedBlogPreviewCardRoute: gettingStartedBlogPreviewCardRoute,
  gettingStartedQrCodeComponentRoute: gettingStartedQrCodeComponentRoute,
  gettingStartedSocialLinksProfileRoute: gettingStartedSocialLinksProfileRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(getting-started)/blog-preview-card",
        "/(getting-started)/qr-code-component",
        "/(getting-started)/social-links-profile"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(getting-started)/blog-preview-card": {
      "filePath": "(getting-started)/blog-preview-card.tsx"
    },
    "/(getting-started)/qr-code-component": {
      "filePath": "(getting-started)/qr-code-component.tsx"
    },
    "/(getting-started)/social-links-profile": {
      "filePath": "(getting-started)/social-links-profile.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
